### ISSUE TITLE
Wrong date output

### ISSUE THREAD

**Issue by misgeatgit** [frectonz/mek-ut-er-ya#1]
Today is እሁድ የካቲት 5 2015 (Sun, Feb 12, 2023). However, the output is wrong.
![Screenshot from 2023-02-12 22-29-10](https://user-images.githubusercontent.com/2872565/218317302-d35bde34-7a51-4d17-9f4e-bbab6f00a1ac.png)

**Comment by frectonz** [comment]
Oww snap same here sth maybe be wrong in the algorithm thanks for reporting it, I will check it out

**Comment by frectonz** [comment]
Seems like the error was in converting Gregorian date to JDN (Julian Day Number), the algorithm i implemented was wrong. So i have decided to use [hifitime](https://docs.rs/hifitime/latest/hifitime/) which seems to have fixed the error.
